---
name: Build and Deploy container image to Amazon Lambda
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      build-image: ${{ steps.build-image.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container
          docker build ./container/
